name: auto-merge

on:
  workflow_dispatch:
    
jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: |
        export BRANCH="$(date "+%Y-%m-%d-%H-%M")"

    - run: echo 'hello world' > hello.txt

    - run: git status
    
    - run: |
        git config --global user.name "${GITHUB_USER}"
        git config --global user.email "${GITHUB_USER}@users.noreply.github.com"
      env: 
        GITHUB_USER: github-actions[bot]

    - run: |
        git switch -c "${BRANCH}"
        git add hello.txt
        git commit -m 'Test'
        git push origin "${BRANCH}"
  
    - run: |
        gh pr create \
          --title 'test' \
          --body 'test' \
          --base 'master' \
          --head "${BRANCH}"

        gh pr merge "${BRANCH}" --auto --squash
        gh pr review "${BRANCH}" --approve
        gh pr close "${BRANCH}" --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
